### ISSUE TITLE
Failure to load markdown viewer on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [nextjournal/viewers#29]
Hi, there is an issue trying to load the markdown viewer on <S-Windows.

To reproduce, just run the markdown test suite

```batch
>powershell -command clojure -X:test/markdown
....
Execution error (PolyglotException) at sun.nio.fs.WindowsPathParser/normalize (WindowsPathParser.java:182).
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/src/viewers/modules/markdown/resources/js/markdown.mjs
```
This is due to an invalid path generated to `markdown.mjs` passed in the graalvm polygot.

Also, the `clojure` cli tool can't seem to be able to download the `clerk` dependency from the `devdocs` module.

```batch
>powershell -command clojure -Stree
Cloning: git@github.com:nextjournal/clerk.git
Error building classpath. Unable to clone C:\Users\ikappaki\.gitlibs\_repos\git@github.com\nextjournal\clerk
FATAL ERROR: No supported authentication methods available (server sent: publickey)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This appears to be due to the `git:/` protocol used for that particular dependency.

PR to follow, thanks.

**Comment by milelo** [comment]
As reported on Slack nextjournal this also causes a startup problem with clerk-demo on Windows:
I've got a small Clerk project I created already running ok on my system.
I'm trying to start:
https://github.com/nextjournal/clerk-demo
from a Windows terminal using "clj" (CLI version 1.10.3.933).
I get a startup exception:
Caused by: org.graalvm.polyglot.PolyglotException: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/mail/.gitlibs/libs/io.github.nextjournal/viewers/1b1374db20b56d14a0f32835c1ce5d9254c23527/modules/markdown/resources/js/markdown.mjs
